version: 0.0.14-{build}
image: Visual Studio 2017
clone_depth: 1
cache:
  - packages -> **\packages.config
configuration: Release
nuget:
  account_feed: true
before_build:
  nuget restore
build:
  include_nuget_references: true
  project: IM.UmbracoSwaggerSync/IM.UmbracoSwaggerSync.csproj
  publish_nuget: true
  verbosity: minimal
deploy:
  - provider: Environment
    name: IM - NuGet Push - LIVE
    on:
      APPVEYOR_REPO_TAG: true